#!/usr/bin/env python3
"""Apply the shared CBT Cards navigation and design metadata to static pages."""

from __future__ import annotations

import argparse
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
STYLE_VERSION = "20260920"

BANNER = (
    '<aside class="vedokrok-banner no-print" data-vedokrok-banner><div class="wrap vedokrok-banner__inner">'
    '<p class="vedokrok-banner__kicker">Now part of</p>'
    '<p class="vedokrok-banner__name"><a href="https://vedokrok.com">Vedokrok</a></p>'
    '<p class="vedokrok-banner__line">CBT Cards proved that compact, actionable techniques are worth keeping. '
    "Vedokrok takes the same practical principle much further: reusable knowledge you can actually use, "
    'across many areas of life and work.</p>'
    '<p class="vedokrok-banner__cta"><a href="https://vedokrok.com">Explore Vedokrok →</a></p>'
    "</div></aside>"
)

FOOTER_LINE = (
    '<p class="vedokrok-footer">Now part of <a href="https://vedokrok.com">Vedokrok</a> — '
    "a broader practical knowledge system.</p>"
)


def section_for(path: Path) -> str:
    rel = path.relative_to(ROOT).as_posix()
    first = rel.split("/", 1)[0]
    if first == "practice":
        return "practice"
    if first == "worksheets":
        return "worksheets"
    if first == "learn":
        return "learn"
    if first in {"library", "toolkit", "research", "agents", "schemas"}:
        return "library"
    if first in {"privacy", "terms", "support", "faq", "contact"}:
        return "support"
    return "about"


def header(no_print: bool) -> str:
    modifier = " no-print" if no_print else ""
    return (
        f'<header class="site-header{modifier}"><div class="wrap nav">'
        '<a class="brand" href="/"><img src="/assets/app-icon.webp" width="46" height="46" alt="" decoding="async" />CBT Cards</a>'
        '<nav class="nav-links" aria-label="Primary">'
        '<a href="/practice/">Practice</a><a href="/learn/">Learn</a>'
        '<a href="/worksheets/">Worksheets</a><a href="/toolkit/">Toolkit</a>'
        '<a href="/agents/">For AI</a><a href="/about/">About</a>'
        '</nav><a class="download" href="/practice/">Find a practice</a>'
        '</div></header>'
    )


def transform(path: Path, source: str) -> str:
    if path == ROOT / "index.html" or "<body" not in source or "Generated by scripts/build_localized_pages.py" in source:
        return source

    result = re.sub(
        r'href="/styles\.css(?:\?v=\d+)?"',
        f'href="/styles.css?v={STYLE_VERSION}"',
        source,
    )
    section = section_for(path)
    result = re.sub(
        r"<body(?![^>]*\bdata-section=)([^>]*)>",
        lambda match: f'<body data-section="{section}"{match.group(1)}>',
        result,
        count=1,
    )
    header_match = re.search(r'<header class="site-header(?: no-print)?">.*?</header>', result, flags=re.S)
    if header_match:
        prefix = "" if "data-vedokrok-banner" in result else BANNER
        result = result[: header_match.start()] + prefix + header("no-print" in header_match.group(0)) + result[header_match.end() :]
    if 'class="vedokrok-footer"' not in result:
        result = re.sub(
            r"(<div>© 2026 CBT Cards.*?</div>)",
            lambda match: match.group(1) + FOOTER_LINE,
            result,
            count=1,
        )
    return result


def main() -> None:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--check", action="store_true")
    args = parser.parse_args()

    stale: list[str] = []
    for path in sorted(ROOT.rglob("*.html")):
        if any(part in {".git", ".codex", ".agents"} for part in path.parts):
            continue
        source = path.read_text(encoding="utf-8")
        expected = transform(path, source)
        if expected == source:
            continue
        if args.write:
            path.write_text(expected, encoding="utf-8")
        else:
            stale.append(path.relative_to(ROOT).as_posix())

    if stale:
        raise SystemExit("design shell is stale: " + ", ".join(stale))
    print("design shell applied" if args.write else "design shell check passed")


if __name__ == "__main__":
    main()
