#!/usr/bin/env python3
"""Generate and verify CBT Cards language hubs and reviewed localized pages."""

from __future__ import annotations

import argparse
import html
import json
import re
from pathlib import Path
from urllib.parse import urlparse

ROOT = Path(__file__).resolve().parents[1]
ORIGIN = "https://cbt-cards.github.io"
SITEMAP_BEGIN = "  <!-- BEGIN GENERATED LOCALIZED URLS -->"
SITEMAP_END = "  <!-- END GENERATED LOCALIZED URLS -->"

LABELS = {
    "ru": {
        "language_name": "Русский",
        "hub_title": "CBT Cards на русском",
        "hub_lede": "Проверенные русские версии материалов CBT Cards. Машинные черновики не публикуются на этих страницах.",
        "resources": "Опубликованные материалы",
        "no_resources": "Проверенных и опубликованных материалов на русском пока нет.",
        "key_points": "Основные пункты",
        "product_relation": "Связь с CBT Cards",
        "safety_scope": "Границы использования",
        "source": "Оригинал на английском",
        "languages": "Языки",
        "about": "О проекте",
        "toolkit": "Инструменты",
    },
    "de": {
        "language_name": "Deutsch",
        "hub_title": "CBT Cards auf Deutsch",
        "hub_lede": "Geprüfte deutsche Versionen von CBT-Cards-Ressourcen. Maschinenentwürfe werden hier nicht veröffentlicht.",
        "resources": "Veröffentlichte Ressourcen",
        "no_resources": "Es gibt noch keine geprüften und veröffentlichten deutschen Ressourcen.",
        "key_points": "Kernpunkte",
        "product_relation": "Bezug zu CBT Cards",
        "safety_scope": "Anwendungsgrenzen",
        "source": "Englische Originalquelle",
        "languages": "Sprachen",
        "about": "Über das Projekt",
        "toolkit": "Werkzeuge",
    },
}


def fail(message: str) -> None:
    raise SystemExit(f"localized page build failed: {message}")


def load_jsonl(path: Path) -> list[dict]:
    records: list[dict] = []
    for line_number, line in enumerate(path.read_text(encoding="utf-8").splitlines(), start=1):
        if not line.strip():
            continue
        try:
            record = json.loads(line)
        except json.JSONDecodeError as exc:
            fail(f"invalid JSONL in {path.relative_to(ROOT)} line {line_number}: {exc}")
        if not isinstance(record, dict):
            fail(f"non-object JSONL record in {path.relative_to(ROOT)} line {line_number}")
        records.append(record)
    return records


def is_published(record: dict) -> bool:
    return (
        record.get("translation_status") == "human_reviewed"
        and record.get("review_status") == "reviewed_for_publication"
        and record.get("publication_status") == "published"
    )


def expected_canonical(locale: str, resource_id: str) -> str:
    return f"{ORIGIN}/{locale}/resources/{resource_id}/"


def local_path_from_url(url: str) -> Path:
    parsed = urlparse(url)
    if f"{parsed.scheme}://{parsed.netloc}" != ORIGIN:
        fail(f"localized canonical is outside CBT Cards origin: {url}")
    if not parsed.path.endswith("/"):
        fail(f"localized canonical must end with '/': {url}")
    return ROOT / parsed.path.lstrip("/") / "index.html"


def esc(value: object) -> str:
    return html.escape(str(value), quote=True)


def page_shell(*, locale: str, title: str, description: str, canonical: str, body: str) -> str:
    return f'''<!doctype html>
<html lang="{esc(locale)}">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width,initial-scale=1" />
<title>{esc(title)}</title>
<meta name="description" content="{esc(description)}" />
<meta name="robots" content="index,follow,max-image-preview:large" />
<link rel="canonical" href="{esc(canonical)}" />
<link rel="stylesheet" href="/styles.css?v=20260818" />
<link rel="icon" href="/assets/app-icon.png" />
</head>
<body>
<!-- Generated by scripts/build_localized_pages.py; edit source data instead. -->
<a class="skip" href="#main">Skip to content</a>
<header class="site-header"><div class="wrap nav"><a class="brand" href="/"><img src="/assets/app-icon.png" width="42" height="42" alt="" />CBT Cards</a><nav class="nav-links" aria-label="Primary"><a href="/learn/">Learn</a><a href="/worksheets/">Worksheets</a><a href="/toolkit/">Toolkit</a><a href="/languages/">Languages</a><a href="/about/">About</a></nav><a class="download" href="/toolkit/">Explore tools</a></div></header>
<main id="main">{body}</main>
<footer class="footer"><div class="wrap footer-grid"><div>© 2026 CBT Cards</div><nav aria-label="Footer"><a href="/languages/">Languages</a><a href="/toolkit/">Toolkit</a><a href="/about/">About</a><a href="/privacy/">Privacy</a></nav></div></footer>
</body>
</html>
'''


def translation_counts(locales: list[dict], translations: list[dict]) -> dict[str, dict[str, int]]:
    counts = {
        item["locale"]: {"total": 0, "machine_draft": 0, "human_reviewed": 0, "published": 0}
        for item in locales
    }
    for record in translations:
        locale = record.get("locale")
        if locale not in counts:
            continue
        counts[locale]["total"] += 1
        status = record.get("translation_status")
        if status in {"machine_draft", "human_reviewed"}:
            counts[locale][status] += 1
        if is_published(record):
            counts[locale]["published"] += 1
    return counts


def render_languages(registry: dict, translations: list[dict], source_count: int) -> str:
    locales = registry["locales"]
    counts = translation_counts(locales, translations)
    rows: list[str] = []
    for item in locales:
        locale = item["locale"]
        status = item["status"]
        if status == "source":
            detail = f"{source_count} canonical source records"
            name = f'<a href="/learn/">{esc(item["native_name"])}</a>'
        else:
            count = counts[locale]
            detail = (
                f'{count["machine_draft"]} machine drafts · '
                f'{count["human_reviewed"]} human-reviewed · '
                f'{count["published"]} published'
            )
            if item.get("public_html") is True:
                name = f'<a href="/{esc(locale)}/">{esc(item["native_name"])}</a>'
            else:
                name = esc(item["native_name"])
        rows.append(
            f'<li><strong>{name}</strong> · <code>{esc(status)}</code><br />'
            f'{esc(detail)}. {esc(item["policy"])}</li>'
        )

    body = f'''
<section class="page-hero"><div class="wrap"><div class="crumb"><a href="/">CBT Cards</a> / Languages</div><h1>Languages and translation status</h1><p class="lede">CBT Cards separates source content, machine translation drafts, human review, and public publication. A translation does not become official merely because a model produced readable text.</p></div></section>
<section class="section alt"><div class="wrap prose">
<h2>Current language status</h2>
<ul>{''.join(rows)}</ul>
<h2>How publication works</h2>
<p>Machine drafts are development data only. A localized resource becomes an official CBT Cards publication only after separate language and editorial review, an explicit publication status, and generation of a canonical public page.</p>
<p>Machine-readable status is available in <a href="/data/locales.json"><code>data/locales.json</code></a> and <a href="/data/translations.jsonl"><code>data/translations.jsonl</code></a>. English source records remain in <a href="/data/knowledge.jsonl"><code>data/knowledge.jsonl</code></a>.</p>
</div></section>'''
    return page_shell(
        locale="en",
        title="CBT Cards languages and translation status",
        description="Language availability, machine-draft coverage, human-review status, and publication rules for CBT Cards localized resources.",
        canonical=f"{ORIGIN}/languages/",
        body=body,
    )


def render_locale_hub(locale_entry: dict, published: list[dict], source_by_id: dict[str, dict]) -> str:
    locale = locale_entry["locale"]
    labels = LABELS.get(locale)
    if labels is None:
        fail(f"no localized page labels configured for public_html locale: {locale}")
    items: list[str] = []
    for record in sorted(published, key=lambda item: item["title"].casefold()):
        source = source_by_id[record["resource_id"]]
        items.append(
            f'<li><a href="/{esc(locale)}/resources/{esc(record["resource_id"])}/">'
            f'{esc(record["title"])}</a><br />{esc(record["summary"])} '
            f'<span class="source-note">({esc(source["type"])})</span></li>'
        )
    if items:
        resource_block = f'<ul>{"".join(items)}</ul>'
    else:
        resource_block = f'<p>{esc(labels["no_resources"])}</p>'

    body = f'''
<section class="page-hero"><div class="wrap"><div class="crumb"><a href="/">CBT Cards</a> / <a href="/languages/">{esc(labels["languages"])}</a> / {esc(labels["language_name"])}</div><h1>{esc(labels["hub_title"])}</h1><p class="lede">{esc(labels["hub_lede"])}</p></div></section>
<section class="section alt"><div class="wrap prose"><h2>{esc(labels["resources"])}</h2>{resource_block}<p><a href="/languages/">← {esc(labels["languages"])}</a></p></div></section>'''
    return page_shell(
        locale=locale,
        title=labels["hub_title"],
        description=labels["hub_lede"],
        canonical=f"{ORIGIN}/{locale}/",
        body=body,
    )


def render_resource(record: dict, source: dict) -> str:
    locale = record["locale"]
    labels = LABELS.get(locale)
    if labels is None:
        fail(f"no localized page labels configured for locale: {locale}")
    points = "".join(f"<li>{esc(point)}</li>" for point in record["key_points"])
    canonical = expected_canonical(locale, record["resource_id"])
    body = f'''
<section class="page-hero"><div class="wrap"><div class="crumb"><a href="/">CBT Cards</a> / <a href="/languages/">{esc(labels["languages"])}</a> / <a href="/{esc(locale)}/">{esc(labels["language_name"])}</a></div><h1>{esc(record["title"])}</h1><p class="lede">{esc(record["summary"])}</p></div></section>
<section class="section alt"><div class="wrap prose">
<h2>{esc(labels["key_points"])}</h2><ul>{points}</ul>
<h2>{esc(labels["product_relation"])}</h2><p>{esc(record["product_relation"])}</p>
<h2>{esc(labels["safety_scope"])}</h2><p>{esc(record["safety_scope"])}</p>
<p class="source-note">{esc(labels["source"])}: <a href="{esc(source["canonical_url"])}">{esc(source["title"])}</a>. Source review snapshot: <time datetime="{esc(record["source_reviewed"])}">{esc(record["source_reviewed"])}</time>. Localized review: <time datetime="{esc(record["reviewed"])}">{esc(record["reviewed"])}</time>.</p>
</div></section>'''
    return page_shell(
        locale=locale,
        title=f'{record["title"]} · CBT Cards',
        description=record["summary"],
        canonical=canonical,
        body=body,
    )


def expected_outputs(registry: dict, knowledge: list[dict], translations: list[dict]) -> tuple[dict[Path, str], list[tuple[str, str]]]:
    locales = registry["locales"]
    source_locale = registry["source_locale"]
    source_by_id = {record["id"]: record for record in knowledge}
    locale_by_id = {item["locale"]: item for item in locales}
    published_by_locale: dict[str, list[dict]] = {item["locale"]: [] for item in locales}

    for record in translations:
        if not is_published(record):
            continue
        locale = record["locale"]
        resource_id = record["resource_id"]
        if locale not in locale_by_id or resource_id not in source_by_id:
            fail(f"published translation references unknown locale/resource: {locale}/{resource_id}")
        if locale_by_id[locale].get("public_html") is not True:
            fail(f"published translation belongs to locale without public_html: {locale}/{resource_id}")
        expected = expected_canonical(locale, resource_id)
        if record.get("canonical_url") != expected:
            fail(f"published translation canonical must be {expected}: {locale}/{resource_id}")
        published_by_locale[locale].append(record)

    outputs: dict[Path, str] = {
        ROOT / "languages" / "index.html": render_languages(registry, translations, len(source_by_id))
    }
    sitemap_entries: list[tuple[str, str]] = [(f"{ORIGIN}/languages/", registry["updated"])]

    for item in locales:
        locale = item["locale"]
        if locale == source_locale or item.get("public_html") is not True:
            continue
        published = published_by_locale[locale]
        outputs[ROOT / locale / "index.html"] = render_locale_hub(item, published, source_by_id)
        hub_lastmod = max([registry["updated"], *[record["reviewed"] for record in published if record.get("reviewed")]])
        sitemap_entries.append((f"{ORIGIN}/{locale}/", hub_lastmod))
        for record in published:
            source = source_by_id[record["resource_id"]]
            path = local_path_from_url(record["canonical_url"])
            outputs[path] = render_resource(record, source)
            sitemap_entries.append((record["canonical_url"], record["reviewed"]))

    return outputs, sitemap_entries


def render_sitemap_block(entries: list[tuple[str, str]]) -> str:
    lines = [SITEMAP_BEGIN]
    for url, lastmod in sorted(entries):
        lines.append(f"  <url><loc>{esc(url)}</loc><lastmod>{esc(lastmod)}</lastmod></url>")
    lines.append(SITEMAP_END)
    return "\n".join(lines)


def replace_sitemap_block(text: str, block: str) -> str:
    pattern = re.compile(re.escape(SITEMAP_BEGIN) + r".*?" + re.escape(SITEMAP_END), re.DOTALL)
    if not pattern.search(text):
        fail("sitemap.xml is missing generated-localized marker block")
    return pattern.sub(block, text, count=1)


def managed_paths(registry: dict) -> set[Path]:
    paths: set[Path] = set()
    languages_page = ROOT / "languages" / "index.html"
    if languages_page.exists():
        paths.add(languages_page)
    source_locale = registry["source_locale"]
    for item in registry["locales"]:
        locale = item["locale"]
        if locale == source_locale:
            continue
        hub = ROOT / locale / "index.html"
        if hub.exists():
            paths.add(hub)
        resources_root = ROOT / locale / "resources"
        if resources_root.exists():
            paths.update(resources_root.glob("*/index.html"))
    return paths


def prune_empty_parents(path: Path, stop: Path) -> None:
    parent = path.parent
    while parent != stop and parent.is_dir():
        try:
            parent.rmdir()
        except OSError:
            break
        parent = parent.parent


def main() -> None:
    parser = argparse.ArgumentParser()
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--check", action="store_true", help="verify generated localized outputs (default)")
    mode.add_argument("--write", action="store_true", help="write generated localized outputs")
    args = parser.parse_args()

    registry = json.loads((ROOT / "data" / "locales.json").read_text(encoding="utf-8"))
    knowledge = load_jsonl(ROOT / "data" / "knowledge.jsonl")
    translations = load_jsonl(ROOT / "data" / "translations.jsonl")
    outputs, sitemap_entries = expected_outputs(registry, knowledge, translations)

    sitemap_path = ROOT / "sitemap.xml"
    sitemap_text = sitemap_path.read_text(encoding="utf-8")
    expected_sitemap = replace_sitemap_block(sitemap_text, render_sitemap_block(sitemap_entries))
    existing_managed = managed_paths(registry)
    expected_paths = set(outputs)

    if args.write:
        for path, content in outputs.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
        for stale in sorted(existing_managed - expected_paths):
            stale.unlink()
            prune_empty_parents(stale, ROOT)
        sitemap_path.write_text(expected_sitemap, encoding="utf-8")
        print(f"localized pages written: {len(outputs)} HTML pages; {len(sitemap_entries)} sitemap URLs")
        return

    errors: list[str] = []
    for path, content in outputs.items():
        if not path.exists():
            errors.append(f"missing generated page: {path.relative_to(ROOT)}")
        elif path.read_text(encoding="utf-8") != content:
            errors.append(f"generated page differs from source data: {path.relative_to(ROOT)}")
    for stale in sorted(existing_managed - expected_paths):
        errors.append(f"stale generated localized page: {stale.relative_to(ROOT)}")
    if sitemap_text != expected_sitemap:
        errors.append("sitemap generated-localized block differs from locale/translation data")

    if errors:
        fail("; ".join(errors))
    print(f"localized page check passed: {len(outputs)} HTML pages; {len(sitemap_entries)} sitemap URLs")


if __name__ == "__main__":
    main()
